default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: ozzy@1414

development:
  <<: *default
  database: editora_development

test:
  <<: *default
  database: editora_test

production:
  <<: *default
  database: editora_production
  username: editora
  password: <%= ENV['EDITORA_DATABASE_PASSWORD'] %>
